
-- Dumping structure for table trampa.blog_posts
CREATE TABLE IF NOT EXISTS `blog_posts` (
  `id` varchar(20) NOT NULL,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `images` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
-- Dumping data for table trampa.blog_posts: ~3 rows (approximately)
INSERT IGNORE INTO `blog_posts` (`id`, `title`, `body`, `images`, `created_at`) VALUES
	('87EB5C110F4DC135932E', 'My First Blog Post', 'This Software Requirements Specification (SRS) document outlines the essential requirements for the development of a mobile application designed to connect users with therapists for love-related issues. By detailing the functional and non-functional requirements, user interfaces, external interfaces, and system architecture, this document serves as a comprehensive guide for all stakeholders involved in the project.\n\nThe application aims to provide a seamless and secure platform where users can seek advice from professional therapists and receive timely responses. With a focus on user experience, data security, and performance, the system is designed to meet the needs of both users and therapists effectively. The outlined requirements and architectural details ensure that the development process is well-structured, reducing the risk of miscommunication and ensuring that the final product aligns with the client\'s vision.\n\nMoving forward, adherence to this SRS will facilitate the successful implementation of the application, ultimately delivering a product that meets the expectations of the end-users and supports the ongoing growth and success of the service.', '["1724577252241.PNG","1724577252252.PNG","1724577252253.PNG","1724577252259.PNG"]', '2024-08-25 09:14:12'),
	('AB84D02F728B0DF197EE', 'My First Blog Post', 'This Software Requirements Specification (SRS) document outlines the essential requirements for the development of a mobile application designed to connect users with therapists for love-related issues. By detailing the functional and non-functional requirements, user interfaces, external interfaces, and system architecture, this document serves as a comprehensive guide for all stakeholders involved in the project.\n\nThe application aims to provide a seamless and secure platform where users can seek advice from professional therapists and receive timely responses. With a focus on user experience, data security, and performance, the system is designed to meet the needs of both users and therapists effectively. The outlined requirements and architectural details ensure that the development process is well-structured, reducing the risk of miscommunication and ensuring that the final product aligns with the client\'s vision.\n\nMoving forward, adherence to this SRS will facilitate the successful implementation of the application, ultimately delivering a product that meets the expectations of the end-users and supports the ongoing growth and success of the service.', '["1724577047402.PNG","1724577047414.PNG","1724577047416.PNG","1724577047430.PNG"]', '2024-08-25 09:10:47'),
	('B20DE105550386F0FFF0', 'My First Blog Post', 'This Software Requirements Specification (SRS) document outlines the essential requirements for the development of a mobile application designed to connect users with therapists for love-related issues. By detailing the functional and non-functional requirements, user interfaces, external interfaces, and system architecture, this document serves as a comprehensive guide for all stakeholders involved in the project.\n\nThe application aims to provide a seamless and secure platform where users can seek advice from professional therapists and receive timely responses. With a focus on user experience, data security, and performance, the system is designed to meet the needs of both users and therapists effectively. The outlined requirements and architectural details ensure that the development process is well-structured, reducing the risk of miscommunication and ensuring that the final product aligns with the client\'s vision.\n\nMoving forward, adherence to this SRS will facilitate the successful implementation of the application, ultimately delivering a product that meets the expectations of the end-users and supports the ongoing growth and success of the service.', '["1724577209980.PNG","1724577209990.PNG","1724577209996.PNG","1724577210003.PNG"]', '2024-08-25 09:13:30');
